In [2]:
#create/write in a text file


In [13]:
#Writing a file
with open("FirstTextFile.txt","w") as file:
    file.write("This my first sentence")

In [10]:
#Read file
with open("FirstTextFile.txt","r") as file:
    file.read()

In [14]:
#Read file with print way 1
with open("FirstTextFile.txt","r") as file:
    print(file.read())
    
    

This my first sentence


In [15]:
#Read file with print way 2
with open("FirstTextFile.txt","r") as file:
    data=file.read()
    print(data)

This my first sentence


In [18]:
with open("FirstTextFile.txt","w") as file:
    file.write("New data")

In [19]:
with open("FirstTextFile.txt","r") as file:
    data=file.read()
    print(data)

New data


In [21]:
#Appending a file 
with open("FirstTextFile.txt","a") as file:
    file.write("Today is Wednesday")

In [22]:
with open("FirstTextFile.txt","r") as file:
    data=file.read()
    print(data)

New dataToday is Wednesday


In [ ]:
#r+ (read +write) 
#w+ (read +write + if a file isnt present, it also creates a file)

In [ ]:
with open("SecondTextFile.txt","r") as file:
        file.write("Today is Wednesday")
    

In [ ]:
#Appending a file 
with open("FirstTextFile.txt","a") as file:
    file.write("Today is Wednesday")

In [2]:
with open("SecondTextFile.txt","r") as file:
        data =file.read()
print(data)

I am adding data into the second text file


In [3]:
#This with won't print without file.seek()
with open("seekfile.txt","w+") as file:
    file.write("THis is the file I have made")
    print(file.read())

In [5]:
#This with will print without file.seek()
with open("seekfile.txt","w+") as file:
    file.write("THis is the file I have made")
    file.seek(0)
    print(file.read())

THis is the file I have made


In [6]:
#This with will print without file.seek()
with open("seekfile.txt","r+") as file:
    file.write("THis is the file  hirdes I have made")
    file.seek(0)
    print(file.read())

THis is the file  hirdes I have made


In [7]:
### CSV FILE WRITING

In [13]:
import csv
with open("ThirdLab.csv","w",newline="") as v:
    data_Handler=csv.writer(v,delimiter=",") #This delimiter space out
    data_Handler.writerow(["Name","Gender","Age"])
    data_Handler.writerow(["Hirdesh","Male","23"])
    data_Handler.writerow(["Kumar","Male","23"])                           

In [14]:
with open("ThirdLab.csv","r") as file:
    for a in file:
        print(file.read())
        #print till the end of file pointer
                #but first row missed find the reason

Hirdesh,Male,23
Kumar,Male,23



In [17]:

with open("ThirdLab.csv","r") as file:
    print(csv.reader(file))


In [18]:
with open("ThirdLab.csv","r") as file:
    dataset=csv.reader(file)
    for d in dataset:
        print(d)
        #correct way print whole table

['Name', 'Gender', 'Age']
['Hirdesh', 'Male', '23']
['Kumar', 'Male', '23']


In [20]:
#appendiing a csv file
with open("ThirdLab.csv","a",newline="") as f:
    data_handler=csv.writer(f)
    data_handler.writerow(["0300","abc@gmail.com","abc"])
    data_handler.writerow(["5000","aaaa","vvc"])

In [21]:
with open("ThirdLab.csv","r") as file:
    dataset=csv.reader(file)
    for d in dataset:
        print(d)
        #correct way print whole table

['Name', 'Gender', 'Age']
['Hirdesh', 'Male', '23']
['Kumar', 'Male', '23']
['0300', 'abc@gmail.com', 'abc']
['5000', 'aaaa', 'vvc']


In [29]:
import math
x = [1,5]
y = [4,9]

dist=math.sqrt(((x[0]-y[0])**2) + ((x[1]-y[1])**2))
print(dist)


5.0


In [11]:
#Numpy
import numpy as np

x=np.zeros((7,7))
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [4]:
#Numpy
import numpy as np

x=np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#Numpy
import numpy as np

x=np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#Numpy
import numpy as np

x=np.ones((4,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
#Numpy
import numpy as np

x=np.empty((4,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:

l=[1,4,5,7]
np.array(l)

array([1, 4, 5, 7])

In [15]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [17]:
x=np.arange(1,100,10)
print(x)

[ 1 11 21 31 41 51 61 71 81 91]


In [19]:
print(x.shape)

(10,)


In [20]:
x=np.zeros((10,10))

In [21]:
x.shape

(10, 10)

In [23]:
y=x.reshape((2,2,5,5))
print(y)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
